import os
from flask import Flask, render_template, jsonify, request


app = Flask(__name__)

countries = {'Central America and the Caribbean': ['Belize',
  'Costa Rica',
  'Cuba',
  'Dominican Rep.',
  'El Salvador',
  'Guatemala',
  'Haiti',
  'Honduras',
  'Jamaica',
  'Mexico',
  'Nicaragua',
  'Panama',
  'Trinidad & Tobago'],
 'Central Asia': ['Kazakhstan',
  'Kyrgyzstan',
  'Tajikistan',
  'Turkmenistan',
  'Uzbekistan',
  'East Asia',
  'China, P.R.',
  'Japan',
  'Korea, North',
  'Korea, South',
  'Mongolia',
  'Taiwan'],
 'Central Europe': ['Albania',
  'Bosnia-Herzegovina',
  'Bulgaria',
  'Croatia',
  'Czech Rep.',
  'Czechoslovakia',
  'Estonia',
  'German DR',
  'Hungary',
  'Kosovo',
  'Latvia',
  'Lithuania',
  'Macedonia, FYR',
  'Montenegro',
  'Poland',
  'Romania',
  'Serbia',
  'Slovak Rep.',
  'Slovenia',
  'Yugoslavia (former)'],
 'Eastern Europe': ['Armenia',
  'Azerbaijan',
  'Belarus',
  'Georgia',
  'Moldova',
  'USSR/Russia',
  'Ukraine'],
 'Middle East': ['Bahrain',
  'Egypt',
  'Iran',
  'Iraq',
  'Israel',
  'Jordan',
  'Kuwait',
  'Lebanon',
  'Oman',
  'Qatar',
  'Saudi Arabia',
  'Syria',
  'Turkey',
  'UAE',
  'Yemen',
  'Yemen, North'],
 'North Africa': ['Algeria', 'Libya', 'Morocco', 'Tunisia'],
 'North America': ['Canada', 'USA'],
 'Oceania': ['Australia', 'Fiji', 'New Zealand', 'Papua New Guinea'],
 'South America': ['Argentina',
  'Bolivia',
  'Brazil',
  'Chile',
  'Colombia',
  'Ecuador',
  'Guyana',
  'Paraguay',
  'Peru',
  'Uruguay',
  'Venezuela'],
 'South Asia': ['Afghanistan',
  'Bangladesh',
  'India',
  'Nepal',
  'Pakistan',
  'Sri Lanka'],
 'South-East Asia': ['Brunei',
  'Cambodia',
  'Indonesia',
  'Laos',
  'Malaysia',
  'Myanmar',
  'Philippines',
  'Singapore',
  'Thailand',
  'Timor Leste',
  'Viet Nam'],
 'Sub-Saharan': ['Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cameroon',
  'Cape Verde',
  'Central African Rep.',
  'Chad',
  'Congo',
  'Congo, Dem. Rep.',
  'Cote d Ivorie',
  'Djibouti',
  'Equatorial Guinea',
  'Eritrea',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Rwanda',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  'Swaziland',
  'Tanzania',
  'Togo',
  'Uganda',
  'Zambia',
  'Zimbabwe'],
 'Western Europe': ['Austria',
  'Belgium',
  'Cyprus',
  'Denmark',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Iceland',
  'Ireland',
  'Italy',
  'Luxembourg',
  'Malta',
  'Netherlands',
  'Norway',
  'Portugal',
  'Spain',
  'Sweden',
  'Switzerland',
  'UK']}

continents = ['Africa', 'Americas', 'Asia & Oceania', 'Europe', 'Middle East']
sub_continents = {'Africa': ['North Africa', 'Sub-Saharan'], \
                  'Americas': ['Central America and the Caribbean', 'North America', 'South America'],\
                 'Asia & Oceania': ['Central Asia', 'East Asia', 'South Asia', 'South-East Asia', 'Oceania'],\
                  'Europe': ['Central Europe', 'Eastern Europe', 'Western Europe']
                 }

@app.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

if __name__ == '__main__':
	app.run()
